# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20170930_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrecord',
            name='name',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
